name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.11.0"
  font_awesome_flutter: ^8.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons_pics.png"
  # adaptive_icon_background: "assets/images/Solid_white.png"
  # adaptive_icon_foreground: "assets/images/logopics.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
     - assets/images/
     